version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: echoforge_test
      POSTGRES_USER: echoforge
      POSTGRES_PASSWORD: echoforge
    ports:
      - "55432:5432"
